[package]
name = "find-duplicated-files"
version = "0.1.0"
authors = ["Michael Winkelmann <michael@winkelmann.site>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
walkdir = "2.3.1"